name: spam_classifier_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas=1.3.3
  - numpy=1.21.2
  - matplotlib=3.4.3
  - scikit-learn=0.24.2
  - nltk=3.6.5
  - seaborn=0.11.2
  - pip
  - pip:
    - tensorflow
